version: '1.0'
services:
  app1: &app
    build: .
    hostname: app1
    environment:
      NODE_ENV: production
      DB_URL: postgres://postgres:12345678@db:5432/postgres
      DB_POOL: 50
      PINO_LOG_LEVEL: debug
    expose:
    - "8080"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
  app2:
    <<: *app
    hostname: app2

    